// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppClose():Promise<void>;

export function LoadConf():Promise<string>;

export function SaveConf(arg1:string):Promise<void>;
