// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppClose() {
  return window['go']['main']['App']['AppClose']();
}

export function LoadConf() {
  return window['go']['main']['App']['LoadConf']();
}

export function SaveConf(arg1) {
  return window['go']['main']['App']['SaveConf'](arg1);
}
